name: soia_dart_example
description: Example showing how to use soia's Dart code generator in a project
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  soia: ^0.2.11
  shelf: ^1.4.0

dev_dependencies:
  lints: ^6.0.0
